load("@cargo//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library")

_COMMON_DEPS = [
    "//feo:libfeo_rust",
    "//feo-log:libfeo_log_rust",
    "//feo-logger:libfeo_logger_rust",
    "//feo-time:libfeo_time_rust",
    "//feo-tracing:libfeo_tracing_rust",
] + all_crate_deps(
    normal = True,
)

rust_library(
    name = "libfeo_mini_adas_rust",
    srcs = [
        "src/activities/components.rs",
        "src/activities/messages.rs",
        "src/activities/mod.rs",
        "src/activities/runtime_adapters.rs",
        "src/config.rs",
        "src/ffi.rs",
        "src/lib.rs",
    ],
    aliases = aliases(),
    crate_name = "feo_mini_adas",
    visibility = ["//visibility:public"],
    deps = _COMMON_DEPS + [
        ":libactivities_cc",
    ],
)

rust_binary(
    name = "adas_primary",
    srcs = [
        "src/bin/adas_primary.rs",
    ],
    visibility = ["//visibility:public"],
    deps = _COMMON_DEPS + [
        ":libfeo_mini_adas_rust",
    ],
)

rust_binary(
    name = "adas_secondary_1",
    srcs = [
        "src/bin/adas_secondary_1.rs",
    ],
    visibility = ["//visibility:public"],
    deps = _COMMON_DEPS + [
        ":libfeo_mini_adas_rust",
    ],
)

rust_binary(
    name = "adas_secondary_2",
    srcs = [
        "src/bin/adas_secondary_2.rs",
    ],
    visibility = ["//visibility:public"],
    deps = _COMMON_DEPS + [
        ":libfeo_mini_adas_rust",
    ],
)

cc_library(
    name = "libactivities_cc",
    srcs = [
        "src/activities.cpp",
    ],
    hdrs = [
        "src/include/activities.h",
    ],
    includes = [
        "src/include",
    ],
)
