@startuml
component "Executor" {
   interface Executor {
        + new(activity_chain)
        + register(Activity)
        + execute()
    }
}

    note right of Executor
        Activity Chain for this example is Hello -> World
    end note

component "Activity" {
   interface Activity {
        + init()
        + step()
        + shutdown()
    }
}

component "Hello" {

}
component "World" {

}


Executor o-- Activity : "manages"
Activity <|.. Hello : "implements"
Activity <|.. World : "implements"

@enduml

